apiVersion: batch/v1
kind: CronJob
metadata:
  name: node-metrics-cronjob
  namespace: one
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: node-metrics
              image: docker.io/rohanrustagi18/one2n-assignment:6618149
              env:
                - name: NODE_EXPORTER_URL
                  valueFrom:
                    secretKeyRef:
                      name: node-exporter-url-secret
                      key: NODE_EXPORTER_URL
                - name: OUTPUT_DIR
                  value: "/data/metrics"
              volumeMounts:
                - name: metrics-data
                  mountPath: /data/metrics
          volumes:
            - name: metrics-data
              persistentVolumeClaim:
                claimName: metrics-pvc
          restartPolicy: OnFailure