apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: one
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      containers:
      - name: node-exporter
        image: quay.io/prometheus/node-exporter:latest
        ports:
        - name: metrics
          containerPort: 9100
        # securityContext:
        #   readOnlyRootFilesystem: true
        #   allowPrivilegeEscalation: false
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
      hostNetwork: true
      # hostPID: true

