name: Build and Push Docker Image to DockerHub Registry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USER }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKER_REPO_NAME: "one2n-assignment"
  VERSION: ${{ secrets.VERSION }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb
          sudo dpkg -i trivy_0.18.3_Linux-64bit.deb

      - name: Build Docker Image
        run: |
          docker build -t "${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_REPO_NAME }}:${{ env.VERSION }}" -f Dockerfile .

      - name: Log in to Docker registry
        run: echo "${{ env.DOCKERHUB_TOKEN }}" | docker login -u "${{ env.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Scan Docker Image
        run: |
          trivy image "${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_REPO_NAME }}:${{ env.VERSION }}"

      - name: Push Docker Image
        run: |
          docker push "${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_REPO_NAME }}:${{ env.VERSION }}"

      - name: Update Application Deployment Version
        run: |
          sed -i "s#\(image:\s*\).*\$#\1docker.io/${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_REPO_NAME }}:${{ env.VERSION }}#" kubernetes/metric-cron.yaml