name: Build and Push Docker Image to DockerHub Registry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USER }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKER_REPO_NAME: "one2n-assignment"
  VERSION: ${{ secrets.VERSION }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb
          sudo dpkg -i trivy_0.18.3_Linux-64bit.deb

      - name: Build Docker Image
        run: |
          docker build -t "${DOCKERHUB_USERNAME}/${DOCKER_REPO_NAME}:${VERSION}" -f Dockerfile .

      - name: Log in to Docker registry
        run: echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

      - name: Scan Docker Image
        run: |
          trivy image "${DOCKERHUB_USERNAME}/${DOCKER_REPO_NAME}:${VERSION}"

      - name: Push Docker Image
        run: |
          docker push "${DOCKERHUB_USERNAME}/${DOCKER_REPO_NAME}:${VERSION}"

      - name: Update Application Deployment Version
        run: |
          sed -i "s#\(image:\s*\).*\$#\1docker.io/${DOCKERHUB_USERNAME}/${DOCKER_REPO_NAME}:${VERSION}#" kubernetes/metric-cron.yaml

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add kubernetes/metric-cron.yaml
          git commit -m "Update image version to ${VERSION} in metric-cron.yaml"
          git push origin main    